version: '3'

services:
  postgres:
    image: postgres:9
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - postgres

  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
    ports:
      - 8080:8080
    depends_on:
      - server
