"""empty message

Revision ID: 33618423604b
Revises: 4b08c2c0a817
Create Date: 2017-07-05 07:06:41.117959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33618423604b'
down_revision = '4b08c2c0a817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('board', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('board', 'created')
    op.drop_column('board', 'updated')
    op.add_column('bullet', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('bullet', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('bullet', 'value',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('bullet', 'created_on')
    op.drop_column('bullet', 'updated_on')
    op.add_column('membership', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('membership', sa.Column('role', sa.Enum('admin', 'contributor', 'viewer', name='roletype'), nullable=False))
    op.add_column('membership', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('membership', 'created')
    op.drop_column('membership', 'role_id')
    op.drop_column('membership', 'updated')
    op.add_column('user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('user', 'created')
    op.drop_column('user', 'updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.add_column('membership', sa.Column('updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('membership', sa.Column('role_id', postgresql.ENUM('admin', 'contributor', 'viewer', name='roletype'), autoincrement=False, nullable=False))
    op.add_column('membership', sa.Column('created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('membership', 'updated_at')
    op.drop_column('membership', 'role')
    op.drop_column('membership', 'created_at')
    op.add_column('bullet', sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('bullet', sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('bullet', 'value',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('bullet', 'updated_at')
    op.drop_column('bullet', 'created_at')
    op.add_column('board', sa.Column('updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('board', sa.Column('created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('board', 'updated_at')
    op.drop_column('board', 'created_at')
    # ### end Alembic commands ###
