"""empty message

Revision ID: d878f39921cb
Revises: 387d20621804
Create Date: 2017-08-04 14:00:44.695940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd878f39921cb'
down_revision = '387d20621804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('bullet', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('bullet', 'value',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bullet', 'value',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bullet', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('board', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
